
export const TOKEN_CREATE = 'TOKEN_CREATE'
export const TOKEN_DELETE = 'TOKEN_DELETE'

export const DRAFT_CREATE = 'DRAFT_CREATE'
export const RECEIVE_ALL_DRAFTS = 'RECEIVE_ALL_DRAFTS'
export const DRAFT_FOCUS = 'DRAFT_FOCUS'
