'use strict'

const tokenTypes = {
  TOKEN_CREATE: 'TOKEN_CREATE',
  TOKEN_DELETE: 'TOKEN_DELETE'
}

const draftTypes = {
  DRAFT_CREATE: 'DRAFT_CREATE',
  RECEIVE_ALL_DRAFTS: 'RECEIVE_ALL_DRAFTS',
  DRAFT_FOCUS: 'DRAFT_FOCUS',
  DRAFT_TITLE_EDIT: 'DRAFT_TITLE_EDIT',
  DRAFT_TITLE_MODIFY: 'DRAFT_TITLE_MODIFY',
  DRAFT_LAST_EDIT_TIME: 'DRAFT_LAST_EDIT_TIME',
  DRAFT_TITLE_SAVE: 'DRAFT_TITLE_SAVE'
}

export {tokenTypes, draftTypes}
